### ISSUE TITLE
Invoke code when built as a standalone app

### ISSUE THREAD

**Issue by godserahul1986** [godserahul1986/component-demo#1]
I built my code using component build -s personApiDemo. How do I invoke my code in that case? As far as I know, it gets executed immediately.

**Comment by godserahul1986** [comment]
Not sure what exactly was the issue. I renamed index.js to person.js just for it to make sense and it worked.

**Comment by sankargorthi** [comment]
I have no idea. A standalone will get invoked immediately as there is no other entry point to it. Not quite sure what the issue you ran into was.
